# Generated by Django 4.2.4 on 2023-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='courses',
            constraint=models.CheckConstraint(check=models.Q(('rating__lte', 5.0)), name='rating_constraint'),
        ),
    ]
