# Generated by Django 4.2.4 on 2023-08-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_product_name_cart_course_name_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
