# Generated by Django 4.2.4 on 2023-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_courses_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='author_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
