# Generated by Django 4.2.4 on 2023-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_usercourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
